### ISSUE TITLE
Battle Gear 4 (standard) No longer working after update

### ISSUE THREAD

**Issue by Retrokrell** [teknogods/teknogods.github.io#152]
Hi.  First time posting here.  Hope this is the right place. Running Battle Gear 4 (standard) with a G29 wheel.  With most current TP update, menus constantly circle to the left.  When I run TP v 1062, it works fine.  Assuming there was a update/change at some point in between versions? Doesn't happen in any other game. Any help is appreciated.  Thank you.

**Comment by sTo0z** [comment]
This space is for the wiki/compatibility pages only. Try raising your issue in our Discord channel, or opening issue against proper GitHub.
